---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.0.118

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[base]
      - recipe[monit]
      - recipe[nginx]
      - recipe[monit::nginx]
      - recipe[ruby]
    verifier:
      inspec_tests:
        - test/smoke/base
        - test/smoke/ruby
        - test/smoke/monit
        - test/smoke/nginx
    attributes: